apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kty-prd-02.webapp
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.slack: demo-alerts
    notifications.argoproj.io/subscribe.on-health-degraded.slack: demo-alerts
  labels:
    app.kubernetes.io/name: webapp
    environment: prod
    cluster: kty-prd-02
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: webapp
  sources:
    - repoURL: ghcr.io/stefanprodan/charts
      chart: podinfo
      targetRevision: 6.7.1
      helm:
        releaseName: webapp
        valueFiles:
          - $values/manifests/clusters/kty-prd-02/values.yaml
          - $values/manifests/webapp/values.yaml
          - $values/manifests/webapp/clusters/kty-prd-02/values.yaml
    - repoURL: https://github.com/deegupt4/k8s-manage-app
      targetRevision: main
      ref: values
  destination:
    name: kty-prd-02
    namespace: webapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
