apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo.nginx-sbx
  namespace: argocd
  labels:
    app.kubernetes.io/name: nginx
    environment: sbx
    cluster: hou-sbx-01
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: nginx
      targetRevision: 22.6.10
      helm:
        releaseName: nginx
        valueFiles:
          - $values/manifests/nginx/clusters/hou-sbx-01/values.yaml
    - repoURL: https://github.com/deegupt4/k8s-manage-app
      targetRevision: main
      ref: values
  destination:
    name: hou-sbx-01
    namespace: nginx-sbx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
