auth:
  existingSecret: database-credentials
  secretKeys:
    adminPasswordKey: postgres-password

primary:
  persistence:
    size: 50Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi

readReplicas:
  replicaCount: 1
  persistence:
    size: 50Gi
