apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo.nginx-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: nginx
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      targetRevision: 18.1.5
      helm:
        releaseName: nginx
        valueFiles:
          - $values/argocd-demo/manifests/values-prod.yaml
    - repoURL: https://github.com/deegupt4/k8s-manage-app
      targetRevision: main
      ref: values
  destination:
    name: kty-prd-01
    namespace: nginx-prod
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
