apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo.nginx-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: nginx
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: nginx
      targetRevision: 22.6.10
      helm:
        releaseName: nginx
        valueFiles:
          - $values/argocd-demo/manifests/values-dev.yaml
    - repoURL: https://github.com/deegupt4/k8s-manage-app
      targetRevision: main
      ref: values
  destination:
    name: kty-dev-01
    namespace: nginx-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
