apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kty-dev-01.webapp
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/deegupt4/k8s-manage-app
        revision: main
        files:
          - path: manifests/webapp/clusters/kty-dev-01/*/config.yaml
  template:
    metadata:
      name: 'kty-dev-01.webapp-{{shard.name}}'
      labels:
        app.kubernetes.io/name: webapp
        environment: dev
        cluster: kty-dev-01
        shard: '{{shard.name}}'
    spec:
      project: webapp
      sources:
        - repoURL: ghcr.io/stefanprodan/charts
          chart: podinfo
          targetRevision: 6.7.1
          helm:
            releaseName: 'webapp-{{shard.name}}'
            valueFiles:
              - $values/manifests/clusters/kty-dev-01/values.yaml
              - $values/manifests/webapp/values.yaml
              - $values/manifests/webapp/clusters/kty-dev-01/values.yaml
              - $values/manifests/webapp/clusters/kty-dev-01/{{shard.name}}/values.yaml
        - repoURL: https://github.com/deegupt4/k8s-manage-app
          targetRevision: main
          ref: values
      destination:
        name: kty-dev-01
        namespace: 'webapp-{{shard.name}}'
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
