replicaCount: 1

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

serverBlock: |-
  server {
    listen 0.0.0.0:8080;
    location / {
      return 200 'Hello from ArgoCD -- DEV\n';
      add_header Content-Type text/plain;
    }
    location /health {
      return 200 'ok\n';
      add_header Content-Type text/plain;
    }
  }
