global:
  imagePullSecrets:
    - name: dockerhub-pull

replicaCount: 4

autoscaling:
  enabled: false

ui:
  color: "#3d6fb5"
  message: "Hello from ArgoCD - DEV"

service:
  type: ClusterIP
  port: 9898

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi
