global:
  imagePullSecrets:
    - name: dockerhub-pull

replicaCount: 2

ui:
  color: "#2ecc71"
  message: "Hello from ArgoCD - PROD"

service:
  type: ClusterIP
  port: 9898

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
